apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-autoscaler
rules:
  - apiGroups: [""]
    resources:
      - nodes
      - pods
      - services
      - replicationcontrollers
      - persistentvolumeclaims
      - namespaces
    verbs: ["list", "watch", "get"]
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
    verbs: ["list", "watch", "get"]
  - apiGroups: ["extensions"]
    resources:
      - deployments
      - replicasets
    verbs: ["list", "watch", "get"]
  - apiGroups: ["storage.k8s.io"]
    resources:
      - csidrivers
      - csinodes
      - csistoragecapacities
      - storageclasses
    verbs: ["list", "watch", "get"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "create", "update"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "watch", "get"]
  - apiGroups: ["autoscaling.k8s.io"]
    resources: ["*"]
    verbs: ["*"]
