apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-cleanup-sa
  namespace: slabai
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-cleanup-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-cleanup-binding
roleRef:
  kind: ClusterRole
  name: pod-cleanup-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: pod-cleanup-sa
  namespace: slabai
