apiVersion: v1
kind: ServiceAccount
metadata:
  name: health-monitor-sa
  namespace: autoheal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: health-monitor-access
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: health-monitor-sa
  namespace: autoheal
