apiVersion: v1
kind: Secret
metadata:
  name: autoheal-secrets
  namespace: autoheal
type: Opaque
stringData:
  # Userservice
  USERSERVICE_MONGO_URI: mongodb+srv://praveen:Seb6fpTxI86qT5Aj@praveen-cluster.kroshwm.mongodb.net/k8s-autoheal:27017
  USERSERVICE_PORT: "3000"
  USERSERVICE_RAZORPAY_KEY_ID: dummykey
  USERSERVICE_RAZORPAY_KEY_SECRET: dummysecret
  USERSERVICE_AWS_SECRET_ACCESS_KEY: eVo1UitDRGVCSm5zS1R5QWthcS81UjJuNXhZamhReHRwNnhSMCtBVw==
  USERSERVICE_AWS_ACCESS_KEY_ID: QUtJQTZHQk1DVTdaRkNJN09RV04=
  USERSERVICE_AWS_REGION: us-west-2
  USERSERVICE_S3_BUCKET_NAME: k8s-autoheal
  USERSERVICE_DOWNLOAD_URL: http://localhost:3000

  # Projectservice
  PROJECTSERVICE_MONGO_URI: mongodb+srv://praveen:Seb6fpTxI86qT5Aj@praveen-cluster.kroshwm.mongodb.net/k8s-autoheal:27017
  PROJECTSERVICE_PORT: "3001"
  PROJECTSERVICE_RAZORPAY_KEY_ID: dummykey
  PROJECTSERVICE_RAZORPAY_KEY_SECRET: dummysecret
  PROJECTSERVICE_AWS_SECRET_ACCESS_KEY: eVo1UitDRGVCSm5zS1R5QWthcS81UjJuNXhZamhReHRwNnhSMCtBVw==
  PROJECTSERVICE_AWS_ACCESS_KEY_ID: QUtJQTZHQk1DVTdaRkNJN09RV04=
  PROJECTSERVICE_AWS_REGION: us-west-2
  PROJECTSERVICE_S3_BUCKET_NAME: k8s-autoheal
  PROJECTSERVICE_DOWNLOAD_URL: http://localhost:3001

  # Paymentservice
  PAYMENTSERVICE_MONGO_URI: mongodb+srv://praveen:Seb6fpTxI86qT5Aj@praveen-cluster.kroshwm.mongodb.net/k8s-autoheal:27017
  PAYMENTSERVICE_PORT: "3002"
  PAYMENTSERVICE_RAZORPAY_KEY_ID: dummykey
  PAYMENTSERVICE_RAZORPAY_KEY_SECRET: dummysecret
  PAYMENTSERVICE_AWS_SECRET_ACCESS_KEY: eVo1UitDRGVCSm5zS1R5QWthcS81UjJuNXhZamhReHRwNnhSMCtBVw==
  PAYMENTSERVICE_AWS_ACCESS_KEY_ID: QUtJQTZHQk1DVTdaRkNJN09RV04=
  PAYMENTSERVICE_AWS_REGION: us-west-2
  PAYMENTSERVICE_S3_BUCKET_NAME: k8s-autoheal
  PAYMENTSERVICE_DOWNLOAD_URL: http://localhost:3002
